name: freetask_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.2
  path: ^1.9.0
  intl: ^0.19.0
  mime: ^1.0.5
  shared_preferences: ^2.3.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
