name: freetask_app
description: A new Flutter project.
publish_to: 'none'
version: 4.1.3+14

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  path: ^1.9.0
  intl: ^0.20.2
  mime: ^2.0.0
  shared_preferences: ^2.3.2
  http_parser: ^4.1.2
  url_launcher: ^6.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2
  socket_io_client: ^3.1.4
  connectivity_plus: ^7.0.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  universal_html: ^2.3.0
  universal_io: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
