name: freetask_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  path: ^1.9.0
  intl: ^0.20.2
  mime: ^2.0.0
  shared_preferences: ^2.3.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
